title: Realtyna MVC Core
description: Realtyna MVC Core documentation
theme: just-the-docs

url: https://code.realtyna.com/mvc-core-docs

aux_links:
  Repository: https://github.com/realtyna/Realtyna-MVC-Core
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.png"
