title: Realtyna MVC Core
description: Realtyna MVC Core documentation
theme: just-the-docs

url: https://realtyna.github.io/mvc-core-docs

aux_links:
  Template Repository: https://github.com/realtyna/Realtyna-MVC-Core
